### ISSUE TITLE
How do you actually stop a chat?

### ISSUE THREAD

**Issue by waltercool** [pejuko/follamac#2]
Hi,

I was just testing this app, is there any way to stop a request? This is a very useful feature, specially when AI is doing allucination.

Great app! Simple and useful! Hope you can add "character cards" in future!

**Comment by pejuko** [comment]
It's possible to stop the chat now. Can you test the main branch?

Thanks for the feedback!

**Comment by waltercool** [comment]
It works fantastic! Thank you so much for your quick solution!
